Repository Metron-Project/metron, pull requests merged in 2024-08, with the labels that each got.

#261 Django-5.0.8
  Pipfile.lock
Labels: dependencies

#264 Use DjLint
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  comicsdb/templates/comicsdb/arc_detail.html
  comicsdb/templates/comicsdb/arc_list.html
  comicsdb/templates/comicsdb/attribution.html
  comicsdb/templates/comicsdb/character_detail.html
  comicsdb/templates/comicsdb/character_list.html
  comicsdb/templates/comicsdb/confirm_delete.html
  comicsdb/templates/comicsdb/contact-success.html
  comicsdb/templates/comicsdb/creator_detail.html
  comicsdb/templates/comicsdb/creator_list.html
  comicsdb/templates/comicsdb/home.html
  comicsdb/templates/comicsdb/imprint_detail.html
  comicsdb/templates/comicsdb/imprint_list.html
  comicsdb/templates/comicsdb/issue_detail.html
  comicsdb/templates/comicsdb/issue_form.html
  comicsdb/templates/comicsdb/issue_list.html
  comicsdb/templates/comicsdb/issue_search_box.html
  comicsdb/templates/comicsdb/model_with_attribution_form.html
  comicsdb/templates/comicsdb/pagination.html
  comicsdb/templates/comicsdb/pagination_issue.html
  comicsdb/templates/comicsdb/publisher_detail.html
  comicsdb/templates/comicsdb/publisher_list.html
  comicsdb/templates/comicsdb/series_detail.html
  comicsdb/templates/comicsdb/series_list.html
  comicsdb/templates/comicsdb/statistics.html
  comicsdb/templates/comicsdb/team_detail.html
  comicsdb/templates/comicsdb/team_list.html
  comicsdb/templates/comicsdb/universe_detail.html
  comicsdb/templates/comicsdb/universe_list.html
  comicsdb/templates/comicsdb/week_list.html
  pyproject.toml
  templates/404.html
  templates/500.html
  templates/base.html
  templates/django/forms/widgets/clearable_file_input.html
  templates/flatpages/default.html
  templates/footer.html
  templates/navbar.html
  templates/registration/login.html
  templates/registration/password_reset_complete.html
  templates/registration/password_reset_confirm.html
  templates/registration/password_reset_done.html
  templates/registration/password_reset_form.html
  users/templates/registration/account_activation_email.html
  users/templates/registration/account_activation_invalid.html
  users/templates/registration/account_activation_sent.html
  users/templates/registration/password_change_done.html
  users/templates/registration/password_change_form.html
  users/templates/registration/signup.html
  users/templates/users/change_password.html
  users/templates/users/change_profile.html
  users/templates/users/customuser_detail.html
Labels: chore

#266 Fix Series Post API
  comicsdb/serializers/series.py
Labels: bug, api

#267 Fix Series API POST method
  comicsdb/serializers/series.py
  comicsdb/views/viewsets.py
Labels: bug, api

#268 Fix Formatting on IssueDetail view
  comicsdb/templates/comicsdb/issue_detail.html
  comicsdb/views/issue.py
Labels: bug

#269 Minor Template Tweaks
  comicsdb/templates/comicsdb/arc_list.html
  comicsdb/templates/comicsdb/character_detail.html
  comicsdb/templates/comicsdb/creator_detail.html
  comicsdb/templates/comicsdb/issue_detail.html
  comicsdb/templates/comicsdb/issue_list.html
  comicsdb/templates/comicsdb/team_list.html
  comicsdb/templates/comicsdb/universe_list.html
Labels: chore

#270 Add DC as an attribution option
  comicsdb/migrations/0031_alter_attribution_source.py
  comicsdb/models/attribution.py
  comicsdb/templates/comicsdb/attribution.html
Labels: enhancement

#271 Add `created_by` field to models
  comicsdb/migrations/0032_add_created_by_fields.py
  comicsdb/models/arc.py
  comicsdb/models/character.py
  comicsdb/models/creator.py
  comicsdb/models/imprint.py
  comicsdb/models/issue.py
  comicsdb/models/publisher.py
  comicsdb/models/series.py
  comicsdb/models/team.py
  comicsdb/models/universe.py
  comicsdb/tests/conftest.py
  comicsdb/tests/test_arc_views.py
  comicsdb/tests/test_character_views.py
  comicsdb/tests/test_creator_views.py
  comicsdb/tests/test_imprint_views.py
  comicsdb/tests/test_management.py
  comicsdb/tests/test_publisher_views.py
  comicsdb/tests/test_series_views.py
  comicsdb/tests/test_team_views.py
  comicsdb/tests/test_universe_views.py
  comicsdb/views/arc.py
  comicsdb/views/character.py
  comicsdb/views/creator.py
  comicsdb/views/imprint.py
  comicsdb/views/publisher.py
  comicsdb/views/series.py
  comicsdb/views/team.py
  comicsdb/views/universe.py
  comicsdb/views/viewsets.py
Labels: enhancement

#272 Refactor `find_changes` management command
  comicsdb/management/commands/find_changes.py
Labels: enhancement

#273 Update to Django-5.1
  Pipfile
  Pipfile.lock
Labels: dependencies

#274 Fix image upload with POST API
  comicsdb/serializers/arc.py
  comicsdb/serializers/character.py
  comicsdb/serializers/creator.py
  comicsdb/serializers/imprint.py
  comicsdb/serializers/issue.py
  comicsdb/serializers/publisher.py
  comicsdb/serializers/team.py
  comicsdb/serializers/universe.py
  comicsdb/views/viewsets.py
Labels: bug
